project:
  type: website
  output-dir: docs

website:
  title: "Modeling BLS damage"
  navbar:
    left:
      - href: index.qmd
        text: "<i class='fas fa-info-circle'></i> About"
      - href: about.qmd
        text: "<i class='fas fa-chart-line'></i> Data Analysis"

format:
  html:
    theme: Minimalist
    css: styles.css
    toc: true

editor: visual
