project:
  type: website
  output-dir: docs
  
website:
  title: "Modeling BLS damage"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: "Data Analysis"
        
format:
  html:
    theme: Minimalist
    css: styles.css
    toc: true

editor: visual

