project:
  type: website
  output-dir: docs

website:
  title: "Modeling BLS damage"
  navbar:
    left:
      - href: index.qmd
        text: "<i class='bi bi-book-half'></i> About"
      - href: about.qmd
        text: "<i class='bi bi-bar-chart-fill'></i> Data Analysis"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    lib_dir: site_libs
    self_contained: false

editor: visual
