project:
  type: website

website:
  title: "Modeling disease-yield relationships and economic damage"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: "Data Analysis"
        
format:
  html:
    theme: Minimalist
    css: styles.css
    toc: true

editor: visual

