project:
  type: website
  output-dir: docs

website:
  title: "Modeling BLS damage"
  navbar:
    left:
      - href: index.qmd
        text: "About"
        icon: fa fa-home
      - href: about.qmd
        text: "Data Analysis"
        icon: fa fa-file-code-o

format:
  html:
    theme: Minimalist
    css: styles.css
    toc: true

editor: visual
